"""recreate schema

Revision ID: 615b5fc2b4ae
Revises: ec16ab983bf8
Create Date: 2025-10-01 21:20:56.066794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '615b5fc2b4ae'
down_revision: Union[str, None] = 'ec16ab983bf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking_groups', sa.Column('event_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_booking_groups_event_id'), 'booking_groups', ['event_id'], unique=False)
    op.create_index(op.f('ix_booking_groups_phone'), 'booking_groups', ['phone'], unique=False)
    op.create_unique_constraint('uix_event_phone', 'booking_groups', ['event_id', 'phone'])
    op.create_foreign_key(None, 'booking_groups', 'events', ['event_id'], ['name'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'booking_groups', type_='foreignkey')
    op.drop_constraint('uix_event_phone', 'booking_groups', type_='unique')
    op.drop_index(op.f('ix_booking_groups_phone'), table_name='booking_groups')
    op.drop_index(op.f('ix_booking_groups_event_id'), table_name='booking_groups')
    op.drop_column('booking_groups', 'event_id')
    # ### end Alembic commands ###
