"""Change event_id to string for bookings

Revision ID: 97534aa52365
Revises: ab3100233144
Create Date: 2025-09-28 17:01:40.986906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97534aa52365'
down_revision: Union[str, None] = 'ab3100233144'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boarding_sessions', sa.Column('event_id', sa.String(), nullable=True))
    op.drop_column('boarding_sessions', 'event_name')
    # Drop the old FK constraint first
    op.drop_constraint('bookings_event_id_fkey', 'bookings', type_='foreignkey')
    # Alter the column type
    op.alter_column('bookings', 'event_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    # Add new FK constraint to events.name
    op.create_foreign_key('bookings_event_id_fkey', 'bookings', 'events', ['event_id'], ['name'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bookings_event_id_fkey', 'bookings', type_='foreignkey')
    op.create_foreign_key('bookings_event_id_fkey', 'bookings', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.alter_column('bookings', 'event_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.add_column('boarding_sessions', sa.Column('event_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('boarding_sessions', 'event_id')
    # ### end Alembic commands ###
